### ISSUE TITLE
Error while testing

### ISSUE THREAD

**Issue by Zumbalamambo** [blackeagle01/Abnormal_Event_Detection#2]
Im getting the following error while testing.... 

```
File "test.py", line 69, in <module>
    X_test=X_test.reshape(-1,227,227,10)
ValueError: cannot reshape array of size 51529 into shape (227,227,10)
```

if i change `X_test=X_test[:,:,frames]` to `X_test=X_test[:,:,:frames]` , it fires index out of bound exception

**Comment by blackeagle01** [comment]
Hi, I have fixed the above issue but cannot verify it since I do not have the trained model file. Kindly re-run the test module and report any further issues encountered. Thanks.
