### ISSUE TITLE
Mean squared error calculation

### ISSUE THREAD

**Issue by Zumbalamambo** [blackeagle01/Abnormal_Event_Detection#3]
Shouln't it be as follows while calculation MSE?

```
def mean_squared_loss(x1, x2):
    diff = x1 - x2
    a, b, c,d,e = diff.shape
```

because diff.shape returns five values or am I making any mistake? in the code that has been committed, it is a,b,c  = diff.shape 

and can you please give a  gist on how to do realtime prediction from webcam?

**Comment by blackeagle01** [comment]
yes, diff.shape will return 5 values, thank you for the correction.Will soon add the feature of real time prediction with webcams.
